#ifndef DALI_GRAPHICS_VK_WRAPPERS_UTILS_TRANSFER_UTILS_HPP_
#define DALI_GRAPHICS_VK_WRAPPERS_UTILS_TRANSFER_UTILS_HPP_

namespace gfx {
class TransferUtils {
public:

private:

}
} // gfx

#endif // DALI_GRAPHICS_VK_WRAPPERS_UTILS_TRANSFER_UTILS_HPP_
